[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = [".oh-my-zsh/custom"]

[".oh-my-zsh/custom/plugins/fzf-zsh-plugin"]
    type = "archive"
    url = "https://github.com/unixorn/fzf-zsh-plugin/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

