# oh-my-zsh and plugins
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = [".oh-my-zsh/custom"]

[".oh-my-zsh/custom/plugins/fzf-zsh-plugin"]
    type = "archive"
    url = "https://github.com/unixorn/fzf-zsh-plugin/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

# tmux plugins
[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripcomponents = 1
    refreshperiod = "168h"

# vim plugins
[".vim/pack/vendor/start/nerdtree"]
    type = "archive"
    url = "https://github.com/preservim/nerdtree/archive/master.tar.gz"
    exact = true
    stripcomponents = 1
    refreshperiod = "168h"

[".vim/pack/vendor/start/papercolor-theme"]
    type = "archive"
    url = "https://github.com/NLKNguyen/papercolor-theme/archive/master.tar.gz"
    exact = true
    stripcomponents = 1
    refreshperiod = "168h"

